export const questions = [
  {
    index: 1,
    question: "성별을 선택하세요.",
    type: "radio",
    options: ["남", "여"],
    id: "gender",
  },
  {
    index: 2,
    question: "나이를 선택해주세요.",
    type: "radio",
    options: ["10대", "20~30대", "40~50대", "60대 이상"],
    id: "age",
  },
  {
    index: 3,
    question: "체형을 선택해주세요.",
    type: "radio",
    options: ["마름", "보통", "살집 있음"],
    id: "shape",
  },
  {
    index: 4,
    question: "운동 목표를 선택해주세요.",
    type: "radio",
    options: ["다이어트", "근육 증진", "재활", "체력 향상"],
    id: "goal",
  },
  {
    index: 5,
    question: "본인의 체력 수준을 선택해주세요.",
    type: "range",
    min: 1,
    max: 5,
    id: "experience",
  },
  {
    index: 6,
    question: "운동을 주로 어디서 하나요?",
    type: "radio",
    options: ["헬스장", "집", "야외", "기타"],
    id: "location",
  },
  {
    index: 7,
    question: "운동하고 싶은 부위를 선택해주세요.",
    type: "checkbox",
    options: ["상체", "하체", "가슴", "등", "어깨", "복부"],
    id: "keyword",
  },
  {
    index: 8,
    question: "주 몇 회 운동하실 예정이신가요?",
    type: "radio",
    options: ["주 1회", "주 2회", "주 3회", "주 4회", "주 5회"],
    id: "frequency",
  },
  {
    index: 9,
    question: "몇 주짜리 프로그램을 원하시나요?",
    type: "radio",
    options: ["1주", "2주", "3주", "4주"],
    id: "duration",
  },
  {
    index: 10,
    question: "운동을 열심히 하실 준비가 되셨나요?",
    type: "radio",
    options: ["네", "아직이요"],
    id: "fighting",
  },
];
